name: CI

on:
  push:
    branches: [ github/3way-diff-gplv2 ]
  pull_request:
    branches: [ github/3way-diff-gplv2 ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: windows-latest

    steps:  
    - uses: actions/checkout@v2

    - name: Build
      run: |
        .\BuildBin.vs2019.cmd
        .\BuildArc.cmd

    - name: Upload zip
      uses: actions/upload-artifact@v2-preview
      with:
        name: frhed.zip
        path: Dist/*.zip
